config-version = 2

persistent-workspaces = []

enable-normalization-flatten-containers = true 
enable-normalization-opposite-orientation-for-nested-containers = true 

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
start-at-login = true

[mode.main.binding]
    cmd-enter = ['exec-and-forget open -n /Applications/Ghostty.app']
    cmd-shift-v = 'exec-and-forget open ~'
    # cmd-d = 'open -a Spotlight' // Done by system shortcut
    cmd-h =         'focus --boundaries-action wrap-around-the-workspace left'
    cmd-j =         'focus --boundaries-action wrap-around-the-workspace down'
    cmd-k =         'focus --boundaries-action wrap-around-the-workspace up'
    cmd-l =         'focus --boundaries-action wrap-around-the-workspace right'

    cmd-shift-h = 'move left'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-l = 'move right'


    alt-f = 'fullscreen'

    cmd-s = 'layout v_accordion'
    cmd-w = 'layout h_accordion'
    cmd-e = 'layout tiles horizontal vertical'

    cmd-shift-space = 'layout floating tiling'

    cmd-1= 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 10'

    ctrl-shift-l = 'move-workspace-to-monitor next'
    ctrl-shift-h = 'move-workspace-to-monitor prev'

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'
    cmd-shift-0 = 'move-node-to-workspace 10'

    alt-shift-c = 'reload-config'

    cmd-r = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'
